In [23]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [24]:
coin=pd.read_csv('BitcoinPrice.csv')

In [25]:
coin

Date         Price
0    2018-08-25 00:00:00   6719.429231
1    2018-08-26 00:00:00   6673.274167
2    2018-08-27 00:00:00   6719.266154
3    2018-08-28 00:00:00   7000.040000
4    2018-08-29 00:00:00   7054.276429
..                   ...           ...
360  2019-08-20 00:00:00  10746.507692
361  2019-08-21 00:00:00  10169.094167
362  2019-08-22 00:00:00  10030.746667
363  2019-08-23 00:00:00  10255.977500
364  2019-08-24 00:00:00  10158.540833

[365 rows x 2 columns]

In [26]:
coin.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Date    365 non-null    object 
 1   Price   365 non-null    float64
dtypes: float64(1), object(1)
memory usage: 5.8+ KB


In [29]:
predictdays=30

In [40]:
coin['prediction']=coin[['Price']].shift(-predictdays)

In [41]:
coin.head()

Price   prediction
0  6719.429231  6639.304167
1  6673.274167  6412.459167
2  6719.266154  6468.631667
3  7000.040000  6535.476667
4  7054.276429  6677.342500

In [38]:
x=np.array(coin.drop(columns=['prediction'],axis=1))


In [42]:
x=x[:len(coin)-predictdays]

In [43]:
x.shape

(335, 1)

In [44]:
x

array([[ 6719.42923077],
       [ 6673.27416667],
       [ 6719.26615385],
       [ 7000.04      ],
       [ 7054.27642857],
       [ 6932.6625    ],
       [ 6981.94615385],
       [ 7100.94666667],
       [ 7247.93538462],
       [ 7260.94923077],
       [ 7326.8525    ],
       [ 7113.06923077],
       [ 6433.27166667],
       [ 6444.80416667],
       [ 6366.1075    ],
       [ 6286.42583333],
       [ 6297.87769231],
       [ 6296.32083333],
       [ 6273.1375    ],
       [ 6450.17923077],
       [ 6499.0625    ],
       [ 6518.655     ],
       [ 6480.64416667],
       [ 6400.60083333],
       [ 6296.63166667],
       [ 6335.82666667],
       [ 6418.56266667],
       [ 6669.99083333],
       [ 6709.3125    ],
       [ 6710.445     ],
       [ 6639.30416667],
       [ 6412.45916667],
       [ 6468.63166667],
       [ 6535.47666667],
       [ 6677.3425    ],
       [ 6550.47416667],
       [ 6593.135     ],
       [ 6590.96833333],
       [ 6562.64166667],
       [ 6470.4025    ],


In [46]:
y=np.array(coin['prediction'])

In [47]:
y=y[:-predictdays]

In [48]:
y.shape

(335,)

In [49]:
y

array([ 6639.30416667,  6412.45916667,  6468.63166667,  6535.47666667,
        6677.3425    ,  6550.47416667,  6593.135     ,  6590.96833333,
        6562.64166667,  6470.4025    ,  6563.62833333,  6568.54916667,
        6581.48666667,  6558.5375    ,  6618.56769231,  6621.71166667,
        6563.00916667,  6248.63583333,  6260.53083333,  6260.64583333,
        6299.39916667,  6452.57166667,  6596.61833333,  6596.27615385,
        6568.04076923,  6487.44416667,  6488.82583333,  6531.60166667,
        6498.48583333,  6481.426     ,  6508.31      ,  6478.0825    ,
        6473.75333333,  6465.9175    ,  6448.22166667,  6382.66833333,
        6309.45285714,  6310.28416667,  6342.28083333,  6387.67416667,
        6363.79583333,  6391.87333333,  6436.965     ,  6445.35416667,
        6538.79      ,  6486.25166667,  6411.28083333,  6399.03333333,
        6378.26833333,  6401.93666667,  6372.06333333,  6176.155     ,
        5615.18      ,  5596.1925    ,  5558.24333333,  5606.04416667,
      

In [50]:
from sklearn.model_selection import train_test_split

In [51]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [52]:
predictarray=np.array(coin.drop(columns=['prediction'],axis=1))[-predictdays:]

In [53]:
print(predictarray)

[[ 9774.2575    ]
 [ 9725.4025    ]
 [ 9500.32416667]
 [ 9533.97933333]
 [ 9539.7125    ]
 [ 9873.81166667]
 [10088.8       ]
 [10478.90166667]
 [10790.63      ]
 [10826.275     ]
 [11713.16166667]
 [11759.01916667]
 [11703.73833333]
 [11803.88833333]
 [11816.9125    ]
 [11586.1725    ]
 [11377.80416667]
 [11397.80166667]
 [11144.38916667]
 [10450.81333333]
 [ 9988.9475    ]
 [10230.73333333]
 [10292.38333333]
 [10295.1175    ]
 [10605.82583333]
 [10746.50769231]
 [10169.09416667]
 [10030.74666667]
 [10255.9775    ]
 [10158.54083333]]


In [56]:
from sklearn.ensemble import RandomForestRegressor

In [57]:
rf=RandomForestRegressor(n_estimators=100,random_state=42)

In [58]:
rf.fit(x_train,y_train)

RandomForestRegressor(random_state=42)

In [59]:
rfpredict=rf.predict(x_test)

In [60]:
rfpredict

array([ 4262.02424936,  3863.08649167,  6258.60719231,  3741.80143462,
        4362.66509167,  7867.74471667,  4197.012     ,  4242.92626667,
       10793.42695   ,  5003.55469167,  6447.84405833,  8314.92919167,
       11565.64379679, 10318.89480833,  3828.50752619,  3752.80341795,
        5315.51069167, 10998.55127167,  5527.94024231, 10212.81783333,
        3691.45613333,  5627.618425  ,  3884.08781346, 10130.29803333,
        6917.45045833,  3882.97883397,  6276.95825   ,  3910.52961667,
        3884.08781346,  4064.38249167,  3900.68856275, 11021.46112051,
        6657.344525  ,  7677.84135   ,  3806.73799167, 10483.53728333,
        4175.71775833, 10421.05761667,  3878.18600513,  8058.10759167,
        4414.862025  ,  6299.03185   ,  3856.20212619,  4420.66347255,
       10356.00915833,  6350.39284167,  5800.0762    ,  4128.81699038,
        6426.70990357,  3643.53631557, 10207.08826667,  3910.89485833,
        4056.635725  ,  3847.42923333,  6652.47891667,  6518.71842051,
      

In [61]:
print('random accuracy: {: .2f}%'.format(rf.score(x_test,y_test)*100))

random accuracy:  83.02%


In [62]:
coin.head()

Price   prediction
0  6719.429231  6639.304167
1  6673.274167  6412.459167
2  6719.266154  6468.631667
3  7000.040000  6535.476667
4  7054.276429  6677.342500